@startuml
skinparam classAttributeIconSize 0

Context <|-- ContextWrapper
Context <|-- ContextImpl
ContextWrapper <|-- ContextThemeWrapper
ContextThemeWrapper <|-- Activity
ContextWrapper <|-- Application
ContextWrapper <|-- Service
abstract class Context{

}

class ContextWrapper{
   Context mBase;
 + ContextWrapper(Context base)
}

class ContextImpl{
 static ContextImpl getImpl(Context context) 
}

class ContextThemeWrapper{

}

class Activity{

}

class Service{

}

class Application{

}
@enduml
